apiVersion: v1
kind: Service
metadata: 
  name: springmvc-cicd-argo-service
sepc:
  type: NodePort
  selector:
    app: springmvc-cicd-argo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
